name: "ci"

env:
    MAIN_BRANCH: "main"

on:
    push:
        branches-ignore:
            -   "main"

    pull_request:
        branches-ignore:
            -   "main"

jobs:
    run-tests:
        runs-on: "ubuntu-latest"
        container:
            image: "faucet/python3:latest"
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4.1.1"
                with:
                    fetch-depth: 0

            -   name: "Install requirements"
                run: "python3 -m pip install -r requirements.txt"

            -   name: "Install coverage library"
                run: "python3 -m pip install coverage"

            -   name: "Run tests"
                timeout-minutes: 1
                run: "python3 tests_run.py"

            -   name: "Do GitHub Action Annotation"
                run: |
                    echo "::group::Coverage"
                    while IFS= read -r line; do
                        file=$(echo "${line}" | cut -d ' ' -f 1)
                        coverage=$(echo "${line}" | cut -d ' ' -f 2)
                        echo "::debug::${file} covered at ${coverage}"
                    done < parsed-coverage.txt
                    echo "::endgroup::"
                    rm -f parsed-coverage.txt

    merge-branch:
        needs:
            -   "run-tests"
        if: "${{ github.event_name == 'push' }}"
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4.1.1"
                with:
                    fetch-depth: 0

            -   name: "Push all commits"
                env:
                    GITHUB_TOKEN: "${{ secrets.PERSONNAL_ACCESS_TOKEN }}"
                run: "git push origin ${{ github.ref_name }}:${{ env.MAIN_BRANCH }}"
